name: Fortify Scan
on:
  push:
    branches:
      - main
 

jobs: 
  build:
    name: Build and analyze Fortify by RB
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Run FoD SAST Scan
        uses: fortify/github-action@v1
        with: 
          sast-scan: true
          
        env: 
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{ secrets.FOD_TENANT }}
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PASSWORD: ${{ secrets.FOD_PAT }}

        
